./ncert_books_download.sh -c 1 -s english -b marigold -l http://ncert.nic.in/textbook/pdf/aeen1dd.zip
./ncert_books_download.sh -c 1 -s english -b raindrop -l http://ncert.nic.in/textbook/pdf/aerd1dd.zip
./ncert_books_download.sh -c 1 -s maths -b math-magic -l http://ncert.nic.in/textbook/pdf/aemh1dd.zip
./ncert_books_download.sh -c 1 -s hindi -b rim-jhim -l http://ncert.nic.in/textbook/pdf/ahhn1dd.zip
./ncert_books_download.sh -c 2 -s english -b marigold -l http://ncert.nic.in/textbook/pdf/been1dd.zip
./ncert_books_download.sh -c 2 -s english -b raindrop -l http://ncert.nic.in/textbook/pdf/berd1dd.zip
./ncert_books_download.sh -c 2 -s maths -b math-magic -l http://ncert.nic.in/textbook/pdf/bemh1dd.zip
./ncert_books_download.sh -c 2 -s hindi -b rim-jhim -l http://ncert.nic.in/textbook/pdf/bhhn1dd.zip
./ncert_books_download.sh -c 3 -s evs -b looking_around -l http://ncert.nic.in/textbook/pdf/ceap1dd.zip
./ncert_books_download.sh -c 3 -s hindi -b rim-jhim -l http://ncert.nic.in/textbook/pdf/chhn1dd.zip
./ncert_books_download.sh -c 3 -s english -b marigold -l http://ncert.nic.in/textbook/pdf/ceen1dd.zip
./ncert_books_download.sh -c 3 -s maths -b math-magic -l http://ncert.nic.in/textbook/pdf/cemh1dd.zip
./ncert_books_download.sh -c 4 -s evs -b looking_around -l http://ncert.nic.in/textbook/pdf/deap1dd.zip
./ncert_books_download.sh -c 4 -s hindi -b rim-jhim -l http://ncert.nic.in/textbook/pdf/dhhn1dd.zip
./ncert_books_download.sh -c 4 -s english -b marigold -l http://ncert.nic.in/textbook/pdf/deen1dd.zip
./ncert_books_download.sh -c 4 -s maths -b math-magic -l http://ncert.nic.in/textbook/pdf/demh1dd.zip
./ncert_books_download.sh -c 5 -s evs -b looking_around -l http://ncert.nic.in/textbook/pdf/eeap1dd.zip
./ncert_books_download.sh -c 5 -s hindi -b rim-jhim -l http://ncert.nic.in/textbook/pdf/ehhn1dd.zip
./ncert_books_download.sh -c 5 -s english -b marigold -l http://ncert.nic.in/textbook/pdf/eeen1dd.zip
./ncert_books_download.sh -c 5 -s maths -b math-magic -l http://ncert.nic.in/textbook/pdf/eemh1dd.zip
./ncert_books_download.sh -c 6 -s hindi -b vasant -l http://ncert.nic.in/textbook/pdf/fhvs1dd.zip
./ncert_books_download.sh -c 6 -s hindi -b durva -l http://ncert.nic.in/textbook/pdf/fhdv1dd.zip
./ncert_books_download.sh -c 6 -s hindi -b bal_rama_katha -l http://ncert.nic.in/textbook/pdf/fhbr1dd.zip
./ncert_books_download.sh -c 6 -s english -b honeysuckle -l http://ncert.nic.in/textbook/pdf/fehl1dd.zip
./ncert_books_download.sh -c 6 -s english -b a_pact_with_the_sun -l http://ncert.nic.in/textbook/pdf/fepw1dd.zip
./ncert_books_download.sh -c 6 -s yoga -b a_helthy_way_of_living -l http://ncert.nic.in/gpEPUB/epub/tiyhwlups1dd.zip
./ncert_books_download.sh -c 6 -s science -b science -l http://ncert.nic.in/textbook/pdf/fesc1dd.zip
./ncert_books_download.sh -c 6 -s sanskrit -b ruchira -l http://ncert.nic.in/textbook/pdf/fhsk1dd.zip
./ncert_books_download.sh -c 6 -s maths -b maths -l http://ncert.nic.in/textbook/pdf/femh1dd.zip
./ncert_books_download.sh -c 7 -s hindi -b vasant -l http://ncert.nic.in/textbook/pdf/ghvs1dd.zip
./ncert_books_download.sh -c 7 -s hindi -b durva -l http://ncert.nic.in/textbook/pdf/ghdv1dd.zip
./ncert_books_download.sh -c 7 -s hindi -b mahabharat -l http://ncert.nic.in/textbook/pdf/ghmb1dd.zip
./ncert_books_download.sh -c 7 -s english -b honeycomb -l http://ncert.nic.in/textbook/pdf/gehc1dd.zip
./ncert_books_download.sh -c 7 -s english -b an_alien_hand__suplpementary_reader -l http://ncert.nic.in/textbook/pdf/geah1dd.zip
./ncert_books_download.sh -c 7 -s yoga -b a_helthy_way_of_living -l http://ncert.nic.in/gpEPUB/epub/tiyhwlups1dd.zip
./ncert_books_download.sh -c 7 -s science -b science -l http://ncert.nic.in/textbook/pdf/gesc1dd.zip
./ncert_books_download.sh -c 7 -s sanskrit -b ruchira -l http://ncert.nic.in/textbook/pdf/ghsk1dd.zip
./ncert_books_download.sh -c 7 -s maths -b maths -l http://ncert.nic.in/textbook/pdf/gemh1dd.zip
./ncert_books_download.sh -c 8 -s hindi -b vasant -l http://ncert.nic.in/textbook/pdf/hhvs1dd.zip
./ncert_books_download.sh -c 8 -s hindi -b durva -l http://ncert.nic.in/textbook/pdf/hhdv1dd.zip
./ncert_books_download.sh -c 8 -s hindi -b bharat_ki_khoj -l http://ncert.nic.in/textbook/pdf/hhbk1dd.zip
./ncert_books_download.sh -c 8 -s english -b honeydew -l http://ncert.nic.in/textbook/pdf/hehd1dd.zip
./ncert_books_download.sh -c 8 -s english -b it_so_happened -l http://ncert.nic.in/textbook/pdf/heih1dd.zip
./ncert_books_download.sh -c 8 -s yoga -b a_helthy_way_of_living -l http://ncert.nic.in/gpEPUB/epub/tiyhwlups1dd.zip
./ncert_books_download.sh -c 8 -s science -b science -l http://ncert.nic.in/textbook/pdf/hesc1dd.zip
./ncert_books_download.sh -c 8 -s sanskrit -b ruchira -l http://ncert.nic.in/textbook/pdf/hhsk1dd.zip
./ncert_books_download.sh -c 8 -s maths -b maths -l http://ncert.nic.in/textbook/pdf/hemh1dd.zip
./ncert_books_download.sh -c 9 -s hindi -b kshitij_hindi_text_book -l http://ncert.nic.in/textbook/pdf/ihks1dd.zip
./ncert_books_download.sh -c 9 -s hindi -b sparsh -l http://ncert.nic.in/textbook/pdf/ihsp1dd.zip
./ncert_books_download.sh -c 9 -s hindi -b kritika -l http://ncert.nic.in/textbook/pdf/ihkr1dd.zip
./ncert_books_download.sh -c 9 -s hindi -b sanchayan -l http://ncert.nic.in/textbook/pdf/ihsa1dd.zip
./ncert_books_download.sh -c 9 -s english -b beehive -l http://ncert.nic.in/textbook/pdf/iebe1dd.zip
./ncert_books_download.sh -c 9 -s english -b moments__supplementary_reader -l http://ncert.nic.in/textbook/pdf/iemo1dd.zip
./ncert_books_download.sh -c 9 -s yoga -b a_helthy_way_of_living -l http://ncert.nic.in/tbEPUB/epub/tiyhwlss1dd.zip
./ncert_books_download.sh -c 9 -s science -b science -l http://ncert.nic.in/textbook/pdf/iesc1dd.zip
./ncert_books_download.sh -c 9 -s sanskrit -b shemushi_prathamo_bhag -l http://ncert.nic.in/textbook/pdf/ihsh1dd.zip
./ncert_books_download.sh -c 9 -s maths -b maths -l http://ncert.nic.in/textbook/pdf/iemh1dd.zip
./ncert_books_download.sh -c 9 -s ict -b ict -l http://ncert.nic.in/textbook/pdf/iict1dd.zip
./ncert_books_download.sh -c 10 -s hindi -b kshitij_hindi_text_book -l http://ncert.nic.in/textbook/pdf/jhks1dd.zip
./ncert_books_download.sh -c 10 -s hindi -b sparsh -l http://ncert.nic.in/textbook/pdf/jhsp1dd.zip
./ncert_books_download.sh -c 10 -s hindi -b kritika -l http://ncert.nic.in/textbook/pdf/jhkr1dd.zip
./ncert_books_download.sh -c 10 -s hindi -b sanchayan -l http://ncert.nic.in/textbook/pdf/jhsy1dd.zip
./ncert_books_download.sh -c 10 -s english -b first_flight -l http://ncert.nic.in/textbook/pdf/jeff1dd.zip
./ncert_books_download.sh -c 10 -s english -b foot_prints_without_feet -l http://ncert.nic.in/textbook/pdf/jefp1dd.zip
./ncert_books_download.sh -c 10 -s yoga -b a_helthy_way_of_living -l http://ncert.nic.in/tbEPUB/epub/tiyhwlss1dd.zip
./ncert_books_download.sh -c 10 -s science -b science -l http://ncert.nic.in/textbook/pdf/jesc1dd.zip
./ncert_books_download.sh -c 10 -s sanskrit -b shemushi -l http://ncert.nic.in/textbook/pdf/jhsk1dd.zip
./ncert_books_download.sh -c 10 -s sanskrit -b abhyaswaran_bhag_2 -l http://ncert.nic.in/textbook/pdf/jsab1dd.zip
./ncert_books_download.sh -c 10 -s maths -b maths -l http://ncert.nic.in/textbook/pdf/jemh1dd.zip
./ncert_books_download.sh -c 10 -s ict -b ict -l http://ncert.nic.in/textbook/pdf/iict1dd.zip
./ncert_books_download.sh -c 11 -s sanskrit -b bhaswati -l http://ncert.nic.in/textbook/pdf/khsk1dd.zip
./ncert_books_download.sh -c 11 -s sanskrit -b shashwathi -l http://ncert.nic.in/textbook/pdf/khsk2dd.zip
./ncert_books_download.sh -c 11 -s accountancy -b accountancy_1 -l http://ncert.nic.in/textbook/pdf/keac1dd.zip
./ncert_books_download.sh -c 11 -s accountancy -b accountancy_1 -l http://ncert.nic.in/textbook/pdf/keac1dd.zip
./ncert_books_download.sh -c 11 -s chemistry -b chemistry_1 -l http://ncert.nic.in/textbook/pdf/kech1dd.zip
./ncert_books_download.sh -c 11 -s chemistry -b chemistry_2 -l http://ncert.nic.in/textbook/pdf/kech2dd.zip
